// === PRACTICAL DECORATION, BACKGROUNDS AND STATUS VISUALS ===
const num=(label,value,min,max,step=.01,kinds)=>({kind:'number',label,default:value,min,max,step,...(kinds?{kinds}:{})});
const select=(label,value,values,kinds)=>({kind:'select',label,default:value,values,...(kinds?{kinds}:{})});
const color=(label,value,kinds)=>({kind:'color',label,default:value,...(kinds?{kinds}:{})});
const bool=(label,value,kinds)=>({kind:'boolean',label,default:value,...(kinds?{kinds}:{})});
export const UTILITY_SCHEMAS={
  highlight:{
    kind:select('Surface light','spotlight',['spotlight','sheen','ripple','sparkle','foil','edge']),
    activation:select('Activation','hover',['auto','hover','press','click','focus','manual']),
    motionSource:select('Light position','pointer',['pointer','auto','both'],['spotlight','foil','edge']),
    radius:num('Light / ripple radius · px',160,8,600,2,['spotlight','ripple','edge']),
    softness:num('Light softness',.75,0,1,.01,['spotlight','sheen','edge']),
    intensity:num('Light intensity',.65,0,2,.02),
    color:color('Primary light','#91e8df'),
    color2:color('Secondary light','#e6b3ee',['foil','sparkle','ripple','sheen']),
    color3:color('Third reflection','#edbf75',['foil']),
    duration:num('Cycle / pulse duration · s',1.4,.1,12,.05,['sheen','ripple','sparkle']),
    interval:num('Automatic repeat interval · s',3,.15,20,.05,['sheen','ripple']),
    angle:num('Light angle · °',-25,-180,180,1,['sheen','foil']),
    bandWidth:num('Sweep band · px',100,4,600,2,['sheen']),
    rippleStyle:select('Ripple drawing','ring',['ring','filled','double'],['ripple']),
    lineWidth:num('Stroke · px',1.8,.25,12,.25,['ripple','edge']),
    count:num('Sparkle count',30,0,120,1,['sparkle']),
    sparkleSize:num('Sparkle size · px',5,1,24,.5,['sparkle']),
    texture:num('Foil microstructure',.4,0,1,.02,['foil']),
    follow:num('Light smoothing · s',.12,0,1,.02,['spotlight','foil','edge']),
    centerX:num('Rest / manual center X',.5,0,1,.01,['spotlight','foil','edge','ripple']),
    centerY:num('Rest / manual center Y · from top',.5,0,1,.01,['spotlight','foil','edge','ripple']),
    clip:bool('Clip to the rounded element',true),
    maxPulses:num('Maximum simultaneous pulses',12,1,40,1,['ripple','sheen']),
    idleIntensity:num('Resting light intensity',0,0,1,.01,['spotlight','foil','edge'])
  },
  backdrop:{
    kind:select('Background composition','mesh',['mesh','bokeh','beams','shadows','waves','contours']),
    color:color('Color A','#246c71'),
    color2:color('Color B','#554f89',['mesh','bokeh','beams','waves','contours']),
    color3:color('Color C','#a76b58',['mesh','bokeh','beams','waves']),
    background:color('Base color','#07191f'),
    transparent:bool('Transparent base',false),
    intensity:num('Layer intensity',.7,0,1.5,.02),
    count:num('Layers / elements',6,1,80,1),
    scale:num('Composition scale',1,.15,4,.05),
    driftSpeed:num('Drift / propagation speed',.2,0,3,.02),
    amplitude:num('Motion / wave amplitude',.25,0,1,.02),
    angle:num('Direction · °',-25,-180,180,1,['mesh','bokeh','beams','shadows']),
    grain:num('Static fine grain',.035,0,.3,.005),
    vignette:num('Edge shading',.2,0,1,.02),
    softness:num('Softness',.8,0,1,.02,['mesh','bokeh','beams','shadows']),
    bokehShape:select('Bokeh aperture','circle',['circle','hexagon','octagon'],['bokeh']),
    lightX:num('Light origin X',.68,-.5,1.5,.01,['beams','shadows']),
    lightY:num('Light origin Y',-.15,-.8,1,.01,['beams','shadows']),
    shadowKind:select('Shadow caster','window',['window','leaves','blinds'],['shadows']),
    edge:select('Wave attachment','bottom',['bottom','top','left','right'],['waves']),
    baseline:num('Wave base position',.62,0,1,.01,['waves']),
    lineWidth:num('Contour stroke · px',1,.25,5,.25,['contours']),
    spacing:num('Contour interval · px',14,4,60,1,['contours'])
  },
  pattern:{
    kind:select('Pattern construction','dots',['dots','grid','crosses','hexagons','diagonal','halftone','arches','tiles']),
    color:color('Pattern ink','#688e94'),
    color2:color('Second ink','#ce9271',['tiles','arches','halftone']),
    background:color('Base','#0b1a22'),
    transparent:bool('Transparent base',true),
    spacing:num('Cell spacing · CSS px',26,6,140,1),
    size:num('Mark size · px',1.4,.2,30,.2,['dots','crosses','halftone']),
    lineWidth:num('Line weight · px',1,.25,8,.25,['grid','crosses','hexagons','diagonal','arches','tiles']),
    angle:num('Rotation · °',0,-180,180,1),
    jitter:num('Construction irregularity',0,0,.45,.01,['dots','crosses']),
    fade:select('Coverage falloff','none',['none','radial','left','right','top','bottom']),
    fadeStrength:num('Falloff strength',.8,0,1,.02),
    driftX:num('Horizontal drift · CSS px/s',0,-80,80,1),
    driftY:num('Vertical drift · CSS px/s',0,-80,80,1),
    halftoneContrast:num('Halftone scale contrast',.8,0,1,.02,['halftone']),
    alternate:bool('Alternate tile orientation',true,['arches','tiles'])
  },
  status:{
    kind:select('Status visualization','skeleton',['skeleton','ring','bar','segments','dots','equalizer']),
    color:color('Active color','#83ddc7'),
    color2:color('Accent color','#bbbef9'),
    trackColor:color('Track / placeholder','#24414b'),
    value:num('Progress value',.65,0,1,.01,['ring','bar','segments']),
    indeterminate:bool('Indeterminate animation',false,['ring','bar','segments']),
    anchorX:num('Center X',.77,0,1,.01),
    anchorY:num('Center Y · from top',.5,0,1,.01),
    size:num('Graphic size · CSS px',100,8,400,2,['ring','dots','equalizer']),
    width:num('Block width · fraction of element',.32,.05,1,.01,['skeleton','bar','segments']),
    thickness:num('Track / bar thickness · px',8,1,50,1,['ring','bar','segments']),
    radius:num('Corner radius · px',8,0,50,1,['skeleton','bar','segments','equalizer']),
    cycle:num('Animation duration · s',2,.4,10,.1),
    count:num('Segments / dots / columns',7,2,40,1,['segments','dots','equalizer']),
    gap:num('Gap · CSS px',12,0,48,1,['segments','skeleton','equalizer']),
    lineHeight:num('Text bar height · CSS px',10,2,32,1,['skeleton']),
    avatarSize:num('Avatar diameter · CSS px',38,12,120,1,['skeleton']),
    avatarGap:num('Avatar / text gap · CSS px',10,0,48,1,['skeleton']),
    sweep:num('Track circumference · degrees',360,30,360,5,['ring']),
    angle:num('Ring start angle · degrees',-90,-180,180,1,['ring']),
    shimmer:bool('Placeholder sheen',true,['skeleton']),
    skeletonLayout:select('Placeholder layout','article',['article','avatar','card','lines'],['skeleton']),
    lines:num('Text placeholder lines',4,1,8,1,['skeleton']),
    amplitude:num('Motion amplitude',.6,0,1,.02,['dots','equalizer']),
    lineCap:select('Stroke cap','round',['round','butt'],['ring']),
    reverse:bool('Reverse direction',false)
  }
};
export const UTILITY_PRESETS={
  highlight:{
    spotlight:{},
    sheen:{kind:'sheen',activation:'hover',color:'#fff5d7',color2:'#8dcddd',intensity:.65},
    ripple:{kind:'ripple',activation:'click',radius:220,duration:.8,intensity:.6,color:'#a3e9dc'},
    sparkle:{kind:'sparkle',activation:'auto',count:30,intensity:.65,color:'#d4f3ee',color2:'#ffd0ab'},
    foil:{kind:'foil',activation:'hover',idleIntensity:.22,color:'#88c9df',color2:'#d79dce',color3:'#eec589',intensity:.4,texture:.32},
    'edge-light':{kind:'edge',activation:'hover',lineWidth:2.3,intensity:1.2,radius:160,color:'#a7edce'},
    'soft-pulse':{kind:'ripple',activation:'auto',rippleStyle:'filled',radius:160,color:'#6cbeb5',duration:2.5,interval:4,intensity:.18},
    'keyboard-focus':{kind:'edge',activation:'focus',motionSource:'auto',intensity:1.1,radius:450,color:'#c1e9ff'},
    'gold-foil':{kind:'foil',activation:'hover',idleIntensity:.3,color:'#c69a48',color2:'#f4d990',color3:'#99835b',texture:.7,intensity:.48}
  },
  backdrop:{
    mesh:{},
    'warm-mesh':{color:'#9a423d',color2:'#b27646',color3:'#5a3e7c',background:'#281820',driftSpeed:.12},
    bokeh:{kind:'bokeh',count:38,scale:.7,color:'#61aaaa',color2:'#d69375',color3:'#b294d6',intensity:.45,driftSpeed:.18,softness:.45},
    sunbeams:{kind:'beams',count:7,color:'#eed6a0',color2:'#c4a279',color3:'#ffdfae',background:'#1c282a',angle:20,intensity:.25,driftSpeed:.14,grain:.018},
    'window-shadows':{kind:'shadows',shadowKind:'window',count:5,color:'#3f544e',background:'#c5b59b',intensity:.5,driftSpeed:.08,grain:.025},
    'leaf-shadows':{kind:'shadows',shadowKind:'leaves',count:25,background:'#bec3a6',color:'#23392d',intensity:.45,driftSpeed:.18,amplitude:.18},
    blinds:{kind:'shadows',shadowKind:'blinds',count:16,background:'#bcaf9a',intensity:.4,driftSpeed:.06},
    'wave-divider':{kind:'waves',count:4,transparent:true,baseline:.65,amplitude:.16,driftSpeed:.25,color:'#639f9b',color2:'#314f74',color3:'#bb9698',grain:0,vignette:0},
    contours:{kind:'contours',count:5,spacing:14,lineWidth:.8,transparent:true,driftSpeed:.05,intensity:.4,color:'#82bbaa',color2:'#b695b7',grain:0,vignette:0}
  },
  pattern:{
    dots:{},grid:{kind:'grid',spacing:40,color:'#477077'},crosses:{kind:'crosses',size:3,spacing:26,color:'#688c8e'},
    hexagons:{kind:'hexagons',spacing:32,color:'#659c94'},diagonal:{kind:'diagonal',spacing:18,color:'#6a859a'},
    halftone:{kind:'halftone',spacing:14,size:5,color:'#738e9a',color2:'#b99d76',halftoneContrast:.9},
    arches:{kind:'arches',spacing:36,color:'#72a292',color2:'#ce996f',size:2},
    tiles:{kind:'tiles',spacing:42,color:'#78aea5',color2:'#d49d74',lineWidth:3},
    'dot-fade':{kind:'dots',spacing:18,size:1.5,fade:'radial',color:'#a4c8bd'},
    blueprint:{kind:'grid',spacing:32,background:'#123346',transparent:false,color:'#54869c',lineWidth:.6}
  },
  status:{
    skeleton:{},'avatar-placeholder':{kind:'skeleton',skeletonLayout:'avatar',lines:3,width:.4},'card-placeholder':{kind:'skeleton',skeletonLayout:'card',width:.29,lines:3},
    'progress-ring':{kind:'ring',sweep:360,size:112,value:.72,thickness:7,color:'#9ad9c3'},
    'progress-bar':{kind:'bar',width:.38,value:.65,thickness:10,color:'#87d2cb'},
    'segmented-progress':{kind:'segments',width:.38,count:12,value:.65,thickness:14,radius:3,gap:4},
    'loading-ring':{kind:'ring',sweep:360,indeterminate:true,size:80,thickness:5,cycle:1.8},
    'loading-dots':{kind:'dots',count:3,size:58,amplitude:.6,cycle:1.3},
    equalizer:{kind:'equalizer',size:110,count:12,gap:4,radius:2,amplitude:.7,cycle:3}
  }
};
